import Head from 'next/head'
import React, { FC } from 'react'

interface LayoutProps {
  children: React.ReactNode | React.ReactChild
}

const Layout:FC <LayoutProps> = ({children}) => {
  return (
    <div className="app">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>header</header>
      <main>{children}</main>
      <footer>footer</footer>
    </div>
  )
}

export default Layout